import type { ProductListItem } from './types';

export const mockProducts: ProductListItem[] = [
  {
    id: 1,
    categoryId: 1,
    categoryName: '원피스',
    name: '플리츠 플로럴 미디 원피스',
    price: 52000,
    originalPrice: 68000,
    discountRate: 24,
    stockQuantity: 38,
    imageUrl: 'https://placehold.co/400x500/f9f0f2/c4788a?text=Dress+01',
    status: 'ON_SALE',
    isNew: true,
    isBest: true,
  },
  {
    id: 2,
    categoryId: 2,
    categoryName: '블라우스',
    name: '린넨 퍼프슬리브 블라우스',
    price: 35000,
    originalPrice: 35000,
    discountRate: 0,
    stockQuantity: 52,
    imageUrl: 'https://placehold.co/400x500/f0f4f9/7899c4?text=Blouse+02',
    status: 'ON_SALE',
    isNew: true,
    isBest: false,
  },
  {
    id: 3,
    categoryId: 3,
    categoryName: '아우터',
    name: '크롭 트위드 재킷',
    price: 89000,
    originalPrice: 120000,
    discountRate: 26,
    stockQuantity: 15,
    imageUrl: 'https://placehold.co/400x500/f5f0eb/c4a278?text=Jacket+03',
    status: 'ON_SALE',
    isNew: false,
    isBest: true,
  },
  {
    id: 4,
    categoryId: 4,
    categoryName: '니트',
    name: '벌키 케이블 니트 베스트',
    price: 45000,
    originalPrice: 58000,
    discountRate: 22,
    stockQuantity: 27,
    imageUrl: 'https://placehold.co/400x500/f0f5f0/7ac478?text=Knit+04',
    status: 'ON_SALE',
    isNew: false,
    isBest: true,
  },
  {
    id: 5,
    categoryId: 5,
    categoryName: '티셔츠',
    name: '오버핏 스트라이프 티셔츠',
    price: 22000,
    originalPrice: 22000,
    discountRate: 0,
    stockQuantity: 80,
    imageUrl: 'https://placehold.co/400x500/f0f0f5/7878c4?text=Tee+05',
    status: 'ON_SALE',
    isNew: true,
    isBest: false,
  },
  {
    id: 6,
    categoryId: 6,
    categoryName: '스커트',
    name: '새틴 랩 미니 스커트',
    price: 31000,
    originalPrice: 42000,
    discountRate: 26,
    stockQuantity: 3,
    imageUrl: 'https://placehold.co/400x500/fdf0f5/c47899?text=Skirt+06',
    status: 'ON_SALE',
    isNew: false,
    isBest: false,
  },
  {
    id: 7,
    categoryId: 7,
    categoryName: '팬츠',
    name: '와이드 슬랙스 팬츠',
    price: 48000,
    originalPrice: 48000,
    discountRate: 0,
    stockQuantity: 44,
    imageUrl: 'https://placehold.co/400x500/f2f2f2/888888?text=Pants+07',
    status: 'ON_SALE',
    isNew: true,
    isBest: true,
  },
  {
    id: 8,
    categoryId: 1,
    categoryName: '원피스',
    name: '셔링 홀터넥 원피스',
    price: 42000,
    originalPrice: 56000,
    discountRate: 25,
    stockQuantity: 19,
    imageUrl: 'https://placehold.co/400x500/f9f4f0/c4a07a?text=Dress+08',
    status: 'ON_SALE',
    isNew: false,
    isBest: false,
  },
  {
    id: 9,
    categoryId: 8,
    categoryName: '블라우스',
    name: '시스루 볼륨 블라우스',
    price: 38000,
    originalPrice: 50000,
    discountRate: 24,
    stockQuantity: 0,
    imageUrl: 'https://placehold.co/400x500/f0f9f4/7ac4a0?text=Blouse+09',
    status: 'SOLD_OUT',
    isNew: false,
    isBest: false,
  },
  {
    id: 10,
    categoryId: 3,
    categoryName: '아우터',
    name: '로브형 롱 코트',
    price: 135000,
    originalPrice: 180000,
    discountRate: 25,
    stockQuantity: 9,
    imageUrl: 'https://placehold.co/400x500/f0ecf9/9878c4?text=Coat+10',
    status: 'ON_SALE',
    isNew: true,
    isBest: false,
  },
  {
    id: 11,
    categoryId: 5,
    categoryName: '티셔츠',
    name: '크롭 그래픽 반팔 티셔츠',
    price: 18000,
    originalPrice: 25000,
    discountRate: 28,
    stockQuantity: 62,
    imageUrl: 'https://placehold.co/400x500/fff0f5/d4789a?text=Tee+11',
    status: 'ON_SALE',
    isNew: false,
    isBest: true,
  },
  {
    id: 12,
    categoryId: 6,
    categoryName: '스커트',
    name: '체크 미디 스커트',
    price: 39000,
    originalPrice: 39000,
    discountRate: 0,
    stockQuantity: 33,
    imageUrl: 'https://placehold.co/400x500/f5f0f0/c49898?text=Skirt+12',
    status: 'ON_SALE',
    isNew: true,
    isBest: false,
  },
];

export const mockBestProducts = mockProducts.filter((p) => p.isBest);
export const mockNewProducts = mockProducts.filter((p) => p.isNew);
export const mockSaleProducts = mockProducts.filter((p) => p.discountRate > 0);
