package com.commerceops.erp.domain.ai.enums;

public enum AiDatasetKey {
    PRODUCTS,
    ORDERS,
    ORDER_DEMAND,
    REVIEWS,
    PRODUCT_REVIEWS,
    INVENTORY_SHIPPING,
    SHIPPING_LEADTIME,
    ACCOUNTING_TRANSACTIONS,
    SETTLEMENT_BATCHES,
    ACCOUNTING_CONSISTENCY_ISSUES
}
