package com.commerceops.erp.domain.audit.enums;

public enum AuditActionType {
    REVIEW_HIDE,
    REVIEW_SHOW,
    REVIEW_DELETE,
    PRODUCT_STATUS_UPDATE,
    PRODUCT_BULK_STATUS_UPDATE,
    PRODUCT_OPERATION_NOTE_CREATE,
    STAFF_CREATED,
    STAFF_UPDATED,
    STAFF_STATUS_CHANGED,
    STAFF_ACTIVE_CHANGED
}
